GET http://localhost:3001/api/ration?count=10&email=ios@xr.test&token=SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1

### get available
GET http://localhost:3001/api/available?email=ios@xr.test&token=SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1

### add available
POST http://localhost:3001/api/available
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "info": {
        "id": "5d480201604483ca13a9ceb0",
        "available": 100,
        "min": 10,
        "max": 0,
        "preferred": 0
    }
}

### remove available
DELETE http://localhost:3001/api/available/
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "id": "5d480201604483ca13a9ceb0"
}

####
GET http://localhost:3001/foods?1

####
POST http://localhost:3001/login
Content-Type: application/json

{
    "clientId": 2
}

####
GET http://localhost:3001/foodSearch?а

####
POST http://localhost:3001/updatePantryInfo
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "updOid": "5a6e114c1940f73e6d61818f",
    "field": "delta",
    "value": 10
}

####
POST http://localhost:3001/removeFromPantry
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "foodId": "5a6ccab519b70038ec83b891"
}

####
POST http://localhost:3001/addToPantry
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "foodId": "5a6ccab519b70038ec83b891"
}

#####
POST https://api.nutritionix.com/v1_1/search

{
    "appId": "1a00fe85",
    "appKey": "41b4d94379febc9ba23d79820d03d4a7",
    "query": "Apple"
}


###
GET https://api.nal.usda.gov/ndb/search/?format=json&q=butter&ds=Standard%20Reference&sort=r&max=50&offset=0&api_key=wjeNXWx9E6vBFvFrBWfoWo9US3czZm0xLLiC84yh

###
GET http://localhost:3001/usda_api/search?args=avocado
###
GET http://localhost:3001/auth/login?email=email@mail.mai&password=12345
Content-Type: application/json
###
GET http://localhost:3001/auth/login

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email":"email@mail.mailaaa",
    "password":"12345" 
}

###
GET http://localhost:3001/api/shoppingList?email=iphone@xs.test&token=e8wyIHnKHtAJnIQ0RjsSiSQ34Ts5qcm4

###
POST http://localhost:3001/api/shoppingList/update
Content-Type: application/json

{
    "email":"iphone@xs.test",
    "token":"e8wyIHnKHtAJnIQ0RjsSiSQ34Ts5qcm4",
    "shoppingList": [
        { "item1": false },
        { "item2": true }
    ],
    "recentPurchases": [
        "item2", "item3", "lalalalalalalalala"
    ]
}