GET http://localhost:3001/ration

####
GET http://localhost:3001/foods

####
POST http://localhost:3001/login
Content-Type: application/json

{
    "clientId": 2
}

####
GET http://localhost:3001/foodSearch?а

####
POST http://localhost:3001/updatePantryInfo
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "updOid": "5a6e114c1940f73e6d61818f",
    "field": "delta",
    "value": 10
}

####
POST http://localhost:3001/removeFromPantry
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "foodId": "5a6ccab519b70038ec83b891"
}

####
POST http://localhost:3001/addToPantry
Content-Type: application/json

{
    "userId": "5a4aafeae02a03d8ebf35361",
    "foodId": "5a6ccab519b70038ec83b891"
}

#####
POST https://api.nutritionix.com/v1_1/search

{
    "appId": "1a00fe85",
    "appKey": "41b4d94379febc9ba23d79820d03d4a7",
    "query": "Apple"
}
