GET http://localhost:3001/api/ration?count=10&email=ios@xr.test&token=SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1

### get available
GET http://localhost:3001/api/available?email=ios@xr.test&token=SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1

### add available
POST http://localhost:3001/api/available
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "info": {
        "id": "5d480201604483ca13a9ceb0",
        "available": 100,
        "min": 10,
        "max": 0,
        "preferred": 0
    }
}

### remove available
DELETE http://localhost:3001/api/available/
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "id": "5d480201604483ca13a9ceb0"
}

### update available
PUT http://localhost:3001/api/available
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "info": {
        "id": "5d480201604483ca13a9ceb0",
        "available": 150,
        "min": 10,
        "max": 150,
        "preferred": 0
    }
}

### get ration (diary)
GET http://localhost:3001/api/ration?email=ios@xr.test&token=SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1&count=1

### prep ration 
POST http://localhost:3001/api/ration
Content-Type: application/json

{
    "email": "ios@xr.test",
    "token": "SqDFWJrUV5yGeiqJuGvckaoJYF5BUqG1",
    "count": 5
}

### search food
GET http://localhost:3001/api/food/search?args=avoca

####
GET http://localhost:3001/foodSearch?rice

###
GET https://api.nal.usda.gov/ndb/search/?format=json&q=rice&ds=Standard%20Reference&sort=r&max=50&offset=0&api_key=wjeNXWx9E6vBFvFrBWfoWo9US3czZm0xLLiC84yh

###
GET http://localhost:3001/usda_api/search?args=rice
###
GET http://localhost:3001/auth/login?email=email@mail.mai&password=12345
Content-Type: application/json
###
GET http://localhost:3001/auth/login

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "email":"email@mail.mailaaa",
    "password":"12345" 
}

###
GET http://localhost:3001/api/shoppingList?email=iphone@xs.test&token=e8wyIHnKHtAJnIQ0RjsSiSQ34Ts5qcm4

###
POST http://localhost:3001/api/shoppingList/update
Content-Type: application/json

{
    "email":"iphone@xs.test",
    "token":"e8wyIHnKHtAJnIQ0RjsSiSQ34Ts5qcm4",
    "shoppingList": [
        { "item1": false },
        { "item2": true }
    ],
    "recentPurchases": [
        "item2", "item3", "lalalalalalalalala"
    ]
}